### ISSUE TITLE
Parameter labels

### ISSUE THREAD

**Issue by iluuu1994** [ooc-lang/rock#818]
The new Swift language has argument labels:

``` swift
func test(param:Int, param2: Float) {}
test(param:10, param2: 10.4)
```

This makes reading the function call much more readable.
Yes, Swift has some crazy rules about when you actually need them and when you can omit them. 
But in general they are very helpful.

That's just an idea I wanna throw out there.

**Comment by iluuu1994** [comment]
This is old 👴🏻😄

**Comment by luciusmagn** [comment]
@iluuu1994 Oooh, is there going to be some development again?

**Comment by iluuu1994** [comment]
@luciusmagn I have not contributed a single line to this project, so definitely not from me 😅

**Comment by luciusmagn** [comment]
Hah, I see. I am just glad to see any activity at all :smile:

**Comment by iluuu1994** [comment]
@luciusmagn Haha I'm just closing old issues, so don't get your hopes up. 😄
