### ISSUE TITLE
Add a simple way of making chained method calls

### ISSUE THREAD

**Issue by h3l1xc** [ooc-lang/rock#973]
It will make code more concise. It's already possible, returning `this` from a method, but it prevents using the return value for something more useful. Here is an example:

`apple := Fruit new() setColor("green") $ setType("apple")`
Here `setType` doesn't refer to the return value of `setColor`, but instead to the last non-chained method (here it's `new`, so it refers to the new instance of Fruit)

**Comment by fasterthanlime** [comment]
Isn't that exactly what `.` does ?

**Comment by h3l1xc** [comment]
Really? I didn't know that! Now I feel dumb :P

**Comment by fasterthanlime** [comment]
Don't feel bad! It must be the first time in six years somebody asks for something we already have ;)
